### PR TITLE
Added gamerule for health limit

### PR DESCRIPTION
**Pull request by Entropy159**
I have added a gamerule to toggle the max health limit of 20 (for compatibility with mods like Pufferfish's Skills and Life Crystals).

### CODE REVIEW

**Comment by Neddslayer** [comment]
I'll review this (hopefully today) when I get the time. It might be better to just remove the health cap altogether, but this seems like a good solution.

**Comment by Neddslayer** [comment]
Please add a translation key to `en_us.json` with a short description of the gamerule and why you would modify it (e.g. improve compatibility with max health-altering mods).

image

**Comment by Neddslayer** [comment]
Other than that, LGTM.

**Comment by Entropy159** [comment]
Done.

**Review by Neddslayer — APPROVED** [review]
LGTM.

**Pull request merged**
